config/routes.rb
Rails.application.routes.draw do
  root "pages#welcome"
  devise_for :contributors, :controllers => { registrations: 'contributors/registrations' }
  resources :contributors, only: [:index, :show]
  resources :ingredients
  resources :blogs

  resources :recipes do
    resources :likes, shallow: true, only: [:create, :destroy]
    resources :comments, shallow: true 
  end
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  belongs_to :contributor, counter_cache: true
  has_many :ingredients
  has_many :instructions
  accepts_nested_attributes_for :ingredients
  accepts_nested_attributes_for :instructions
  has_many :comments, :dependent => :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_contributor!, except: [:index, :show]
  before_action :authorise_contributor!, only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe
    @likes = @recipe.likes_count
    @like = Like.find_or_initialize_by(recipe: @recipe, contributor: current_contributor)
    @comments = @recipe.comments.all
    @comment = @recipe.comments.new
  end

  def new
    @recipe = Recipe.new
    3.times { @recipe.instructions.build }
    @recipe.ingredients.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.contributor = current_contributor

    if @recipe.save 
      redirect_to @recipe
      flash[:notice] = "Recipe created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe
  end

  def update
    if @recipe.update(recipe_params)
      flash[:notice] = "Recipe updated successfully"
      redirect_to @recipe
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end
  
  private

    def recipe_params
      params.require(:recipe).permit(
        :title, :contributor_id, :description, 
        ingredients_attributes: [ :name, :id ],
        instructions_attributes: [ :directions, :id ]
        )
    end

    def find_recipe
      @recipe = Recipe.find(params[:id])
    end

    def authorise_contributor!
      if current_contributor != @recipe.contributor
        flash[:alert] = "You are not the contributor for this recipe!"
        redirect_to @recipe
        return
      end
    end
end

app/views/recipes/_form.html.erb
<%= form_with model: @recipe do |recipe_form| %>
  <div>
    <%= recipe_form.label :title, class:"text-emerald-900" %>
  </div>
  <div>
    <%= recipe_form.text_field :title, autofocus: true, placeholder: :title, class:"w-full rounded-lg border-emerald-800 focus:border-emerald-600 caret-emerald-600 ring-0 focus:ring-emerald-500 text-m font-semibold" %>
  </div>
  <div class="pb-5"></div>
  <div>
    <%= recipe_form.label :description, class:"text-emerald-900" %><i>(Why will we love this recipe?)</i>
  </div>
  <div>
    <%= recipe_form.text_field :description, placeholder: "You will love this recipe because ...", class:"w-full rounded-lg border-emerald-800 focus:border-emerald-600 caret-emerald-600 ring-0 focus:ring-emerald-500 text-m font-semibold" %>
  </div>
  <div class="pb-5"></div>

  <div>
    <%= recipe_form.fields_for :ingredients do |ingredient_form| %>
      <%= ingredient_form.label :ingredient, class:"text-emerald-900" %>
      <%= ingredient_form.text_field :name, class:"w-full rounded-lg border-emerald-800 focus:border-emerald-600 caret-emerald-600 ring-0 focus:ring-emerald-500 text-m font-semibold" %>
    <% end %>
  </div>

  <div>
    <%= recipe_form.fields_for :instructions do |instruction_form| %>
      <%= instruction_form.label :directions, class:"text-emerald-900" %>
      <%= instruction_form.text_field :directions, autofocus: true, placeholder: "How do we make it?!", class:"w-full rounded-lg border-emerald-800 focus:border-emerald-600 caret-emerald-600 ring-0 focus:ring-emerald-500 text-m font-semibold" %>
    <% end %> 
  </div>

  <div>
    <% @recipe.errors.full_messages_for(:title).each do |message| %>
      <div class="italic font-mono text-yellow-300 font-light text-sm"><%= message %></div>
    <% end %>
  </div>
  <div class="pb-5"></div>
  <div>
    <%= recipe_form.submit class:"btn-primary" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="flex space-y-4 p-10">
  <span class="text-center text-emerald-900 font-semibold text-2xl"> 
    <h1>Edit <%= @recipe.title %> </h1>
  </span>
</div>

<%= render "form", recipe: @recipe %>

app/views/recipes/index.html.erb
<div class="flex space-y-4 p-10">
    <span class="text-right text-emerald-900 font-semibold text-xl"> <h1>Welcome to the Recipes Index</h1></span>
</div>

<ul>
  <% @recipes.each do |recipe| %>
   <li class="text-lg text-emerald-900 hover:text-green-500"> <%= link_to recipe.title, recipe %> </li>
   <br>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<div class="flex p-10">
  <span class="text-center text-emerald-900 font-semibold text-2xl">
    <h1>New Recipe Page</h1>
  </span>
</div>

<%= render "form", recipe: @recipe %>

app/views/recipes/show.html.erb
<div class="flex p-10 flex-col">
  <span class="text-center text-emerald-900 font-semibold text-2xl">
    <h1><%= @recipe.title %></h1>
  </span>
  <div class="pb-5"></div>
  <q class="text-emerald-900 text-m"><%= @recipe.description %></q>
    <br>
  <p class="text-m text-emerald-900 hover:text-green-500 underline">by <%= link_to @recipe.contributor.profile_name, @recipe.contributor %></p>
    <div class="pb-5"></div>
  <div>
    <h4 class="text-emerald-900 font-semibold text-m">This recipe uses the following ingredients:</h4>
    <div class="pb-5"></div>
    <ul>
      <% @recipe.ingredients.each do |ing| %>
        <li> <%= ing.name %></li>
      <% end %>
    </ul>
    <div class="pb-5"></div>
  </div>
  <div>
    <h4 class="text-emerald-900 font-semibold text-m">Here's how to make it!</h4>
    <div class="pb-5"></div>
    <ul>
      <% @recipe.instructions.each do |instruction| %>
      <li><%= instruction.directions %>
      <% end %>
    </ul>
    <br>
    <p>Like count: <%= @recipe.likes_count %> </p>
    <% if @like.new_record? %>
    <br>
      <p>Like this idea?</p>
      <%= render 'likes/form' %>
    <% else %>
          <%#= render 'likes/form', @like, data: { "turbo-method": :delete } %>

      <%= button_to 'Unlike', @like,
              method: :delete,
              data: { confirm: "Are you sure?" }, class:"btn-primary" %>  
    <% end %>
  </div>
  <div class="pb-5"></div>
  <h6 class="text-emerald-900 font-semibold text-m"> <%= @comments.size %> comments: </h6>
  <br>
  <%= render @comments %>
  <br>
  <%= render 'comments/form' %>
</div>
<% if @recipe.contributor == current_contributor %>
  <h3 class="text-emerald-900"><i>You contributed this recipe! Thanks for getting involved, </i><i><%= current_contributor.profile_name %>!</i></h3>
  <div class="pb-5"></div>
  <button class="btn-primary w-36"> <%= link_to "Edit", edit_recipe_path(@recipe) %> </button>
<% end %>