config/routes.rb
Rails.application.routes.draw do
  root "pages#welcome"
  devise_for :contributors, :controllers => { registrations: 'contributors/registrations' }
  resources :contributors, only: [:index, :show]
  resources :ingredients
  resources :blogs

  resources :recipes do
    resources :likes, shallow: true, only: [:create, :destroy]
    resources :comments, shallow: true 
  end
  
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :trackable and :omniauthable and :confirmable, :lockable, :timeoutable

  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable 
  validates :profile_name, presence: true, uniqueness: true
  has_many :recipes, :dependent => :destroy
  has_many :blogs, :dependent => :destroy
  has_many :comments, :dependent => :destroy
end

app/controllers/contributors/confirmations_controller.rb
# frozen_string_literal: true

class Contributors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/contributors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Contributors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/contributors/passwords_controller.rb
# frozen_string_literal: true

class Contributors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/contributors/registrations_controller.rb
# frozen_string_literal: true

class Contributors::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
   def update
     super
   end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_name])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:profile_name, :email, :profile_name, :id, :twitter, :instagram, :tiktok, :bio, :facebook, :website, :pinterest])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/contributors/sessions_controller.rb
# frozen_string_literal: true

class Contributors::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:profile_name])
   end
end

app/controllers/contributors/unlocks_controller.rb
# frozen_string_literal: true

class Contributors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController

  def index
    @contributors = Contributor.all
  end

  def show
    @contributor = Contributor.find(params[:id])
  end

  # The following commented out text has been moved to the registrations_controller
  # def edit
  #   @contributor
  # end

  # def update
  #   if @contributor.update(contributor_params)
  #     flash[:notice] = "Profile updated successfully"
  #     redirect_to @contributor
  #   else
  #     render :edit, status: :unprocessable_entity
  #   end
  # end

  private

  def contributor_params
    params.require(:contributor).permit(:email, :profile_name, :id, :twitter, :instagram, :tiktok, :bio, :facebook, :website, :pinterest)
  end

end

app/views/contributors/_profile.html.erb
<div class="pb-5"></div>
<h2 class="text-centre text-emerald-900 font-semibold text-lg">About:</h2>
<ul>
<% if contributor.bio? %>
  <li class="italic text-centre text-emerald-900"><%= contributor.bio %></li>
<% elsif contributor == current_contributor %>
  <li><%= link_to "Add bio", edit_contributor_registration_path(contributor), class:"btn-secondary"%></li>
<% end %>
<br>
<% if contributor.website? %>
  <li class="text-emerald-900 hover:text-green-500"><a href="<%= contributor.website %>">Website</a></li>
</li>
<% elsif contributor == current_contributor %>
  <li class="my-2"><%= link_to "Add website", edit_contributor_registration_path(contributor), class:"btn-secondary"%></li>
<% end %>
<% if contributor.twitter? %>
  <li class="text-emerald-900 hover:text-green-500"><a href="<%= contributor.twitter %>">Twitter</a></li>
<% elsif contributor == current_contributor %>
  <li><%= link_to "Add twitter", edit_contributor_registration_path(contributor), class:"btn-secondary"%></li>
<% end %>
</ul>
<div class="pb-5"></div>

<h2 class="text-centre text-emerald-900 font-semibold text-lg"> Recipe Contributions: <%= contributor.recipes_count %><h3>
<div class="pb-5"></div>
<div>
  <ul>
    <% contributor.recipes.each do |recipe| %>
      <li class="text-lg text-emerald-900 hover:text-green-500"><%= link_to recipe.title, recipe %></li>
      <br>
    <% end %>
  </ul>
</div>
<div class="pb-5"></div>
<div>
  <h2 class="text-centre text-emerald-900 font-semibold text-lg"><%= @contributor.profile_name %>'s Ingredients</h2>
  <br>
  <ul><% contributor.recipes.each do |recipe| %>
      <% recipe.ingredients.each do |ingredient| %>
        <li><%= ingredient.name %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/contributors/index.html.erb
<div class="flex space-y-4 p-10">
    <span class="text-right text-emerald-900 font-semibold text-xl"> <h2>Thanks to our contributors:</h2></span>
</div>

<ul>
  <% @contributors.each do |c| %>
   <li class="text-lg text-emerald-900 hover:text-green-500"> <%= link_to c.profile_name, contributor_path(c) %> </li>
   <br>
  <% end %>
</ul>

app/views/contributors/show.html.erb
<div class="pb-5"></div>

<% if @contributor == current_contributor %>
    <h1 class="text-centre text-emerald-900 font-semibold text-xl"> Welcome to YOUR public profile, <%= current_contributor.profile_name %>! <h1>
     <%= render "profile", contributor: current_contributor %>
<% else %>
    <h1 class="text-centre text-emerald-900 font-semibold text-xl"> Welcome to the public profile for <%= @contributor.profile_name %>: </h1>
     <%= render "profile", contributor: @contributor %>
<% end %>