config/routes.rb
Rails.application.routes.draw do
  root "pages#welcome"
  devise_for :contributors, :controllers => { registrations: 'contributors/registrations' }
  resources :contributors, only: [:index, :show]
  resources :ingredients
  resources :blogs

  resources :recipes do
    resources :likes, shallow: true, only: [:create, :destroy]
    resources :comments, shallow: true 
  end
  
end

app/views/layouts/_header.html.erb
<header>
  <nav class="absolute inset-x-0 top-0 flex justify-between p-6 bg-emerald-800 w-screen">
    <ul class="list-none flex w-full space-x-6 text-lg text-right">
      <li class="text-right space-y-6 underline decoration-1 decoration-indigo-500 font-bold text-white hover:text-green-500"><%= link_to 'Recipes', recipes_path %></li>
      <li class="text-right space-y-6 underline decoration-1 decoration-indigo-500 font-bold text-white hover:text-green-500"><%= link_to 'Ingredients', ingredients_path %></li>
      <li class="text-right space-y-6 underline decoration-1 decoration-indigo-500 font-bold text-white hover:text-green-500"><%= link_to 'Blog', blogs_path %></li>
      <li class="text-right text-white hover:text-emerald-600"><%= link_to "Contributors", contributors_path %></li>



      <% if contributor_signed_in? %>
          <li class="text-right text-white hover:text-emerald-600"><%= link_to 'New Recipe', new_recipe_path %></li>
          <li class="text-right text-white hover:text-emerald-600"><%= link_to 'Profile', contributor_path(current_contributor) %></li>
          <li class="text-right text-white hover:text-emerald-600 !ml-auto"><%= button_to "Sign Out", destroy_contributor_session_path, method: :delete %></li>

      <% else %>
        <li class="text-right text-white hover:text-emerald-300">
          <%= link_to "Sign In", new_contributor_session_path %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipeshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-emerald-50">
    <main class="h-screen flex flex-col flex-grow container mx-auto mt-20 px-5"> 
    <%= render "layouts/header" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>